import { Button } from "@/components/ui/button";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home - Anoty",
  description: "Generated by create next app",
};

export default function HomePage() {
  return (
    <main className="h-full w-full flex items-center justify-center flex-col">
      <div className="text-center space-y-4">
        <div>
          <h1 className="text-3xl">Crie anotações incríveis</h1>
          <p className="text-sm text-muted-foreground">
            Guarde todas as suas anotações em uma única plataforma
          </p>
        </div>

        <Button>Criar conta gratuitamente</Button>
      </div>
    </main>
  );
}
